# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 01:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(auto_created=True)),
                ('codigo', models.CharField(max_length=15)),
                ('valor', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Donaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashca.Codigo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('clave', models.CharField(max_length=5)),
                ('cantidadbase', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidadalcanzada', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_limite', models.DateTimeField()),
                ('video', models.FileField(max_length=200, upload_to='video/')),
            ],
        ),
        migrations.AddField(
            model_name='codigo',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashca.Proyecto'),
        ),
    ]
